### ISSUE TITLE
interaction with ckanext-disqus

### ISSUE THREAD

**Issue by tobybellwood** [conwetlab/ckanext-datarequests#24]
Hi,

Can you advise if comments left on data requests will be handled by ckanext-disqus if installed (https://github.com/ckan/ckanext-disqus), or is it via a different mechanism?

Thanks!

**Comment by aitormagan** [comment]
Comments left are handled by a separated mechanism. But I think it is easy to integrate with the discus extension since some projects (such as data.beta.nyc) are using data requests integrates with Disqus. 


Aitor Magán García

**Comment by tobybellwood** [comment]
Thanks @aitormagan - I'll let you know how we go!

**Comment by aitormagan** [comment]
That's great! If you let me know I will write a wiki page so other users can take advantage of that integration :)

**Comment by tobybellwood** [comment]
Haven't done anything yet ourselves, but for note, it is in use with disqus at:

Open Data Northern Ireland
https://www.opendatani.gov.uk/datarequest (https://github.com/okfn/ckanext-opendatani)

Western Pennsylvania Regional Data Center
https://data.wprdc.org/datarequest (https://github.com/UCSUR-Pitt/ckanext-wprdctheme)

**Comment by aitormagan** [comment]
Thank you so much for your integration. I was aware of the Northern Ireland instance but not of the Pennsylvania one. It's great to see that they are using this extension! :) :) 

Have you been able to integrate the extension with Disqus within your instance?

Please, let me know if you have any issue.

**Comment by Starl3n** [comment]
data.beta.nyc currently have an integration between Data Requests and Discourse rather than Disqus. 

Regarding Disqus it looks like it will work fine as the data request detail pages have a unique path, so it is just a matter of displaying the widget within the template for those pages :)

**Comment by tobybellwood** [comment]
We've just deployed this to http://data.gov.au/datarequest.  Thanks so much for the plugin.  I'm just working on a script to upload our request history from IdeaScale.

**Comment by aitormagan** [comment]
Glad to heard that!! :)

Thank you so much for sharing your instance with us!!

**Comment by aitormagan** [comment]
In case someone is also interested on this, this is the code that you have used to integrate this plugin with Disqus: https://github.com/DataShades/ckanext-datarequests/commit/9c18f62f811824aa89d5accff4cebf5858722119 (Simple & Clean 😄 )

Given that you have managed to solve the integration I will close the issue now! If you have any extra doubt, please do not hesitate to contact us again! :)
