### ISSUE TITLE
AttributeError: 'module' object has no attribute 'redirect'

### ISSUE THREAD

**Issue by owl17** [conwetlab/ckanext-datarequests#26]
Hi,
After I submit data request application, my webpage show server error.
Here is my apache2 error log. 

![Apache Log](https://user-images.githubusercontent.com/4654433/30410141-e6c52d9a-993b-11e7-8963-8899795f2753.png)

I also look into base.py and I didn't found any **redirect** function also.
Please help, thank you

**Comment by mattfullerton** [comment]
This functionality was moved and some extensions need to be updated. You can see a simple way to rewrite the code so that you still have access to a function called redirect here:
https://github.com/derilinx/ckanext-issues/commit/035fcdde856d904c23efc3bc29a2c78730dfa67d?diff=split

**Comment by mattfullerton** [comment]
Affected lines are:
https://github.com/conwetlab/ckanext-datarequests/blob/master/ckanext/datarequests/controllers/ui_controller.py#L177
https://github.com/conwetlab/ckanext-datarequests/blob/master/ckanext/datarequests/controllers/ui_controller.py#L262
https://github.com/conwetlab/ckanext-datarequests/blob/master/ckanext/datarequests/tests/test_ui_controller.py#L217

**Comment by owl17** [comment]
@mattfullerton 
Thanks for your solution! It works like a charm!

**Comment by aitormagan** [comment]
Thanks you both for the solution. We will try to fix that in future versions in order to be compatible with the latest CKAN versions. @owl17, if you prefer, you can create a PR with the changes. 

Aitor Magán García

**Comment by owl17** [comment]
@aitormagan 
Sure, please give me some time
