### ISSUE TITLE
datarequests plugin throws `UndefinedError: 'group_type' is undefined` in `ckan-2.8.0`

### ISSUE THREAD

**Issue by abrahamy** [conwetlab/ckanext-datarequests#36]
In `ckan-2.8.0` the template `organization/read_base.html` has an extra context variable named `group_type`. This template is extended by `organization/datarequests.html` without providing the extra context variable which causes the exception `UndefinedError: 'group_type' is undefined` to be raised when this extension is used with `ckan-2.8.0`.

**Comment by aitormagan** [comment]
This issue will be fixed with the version 1.1.0 of the extension that provides support for CKAN 2.8.0. Thank you for your contribution :)

**Comment by aitormagan** [comment]
Close as version 1.1.0 fixes this issue.
