### ISSUE TITLE
typo in the new_comment templates

### ISSUE THREAD

**Issue by nykc** [conwetlab/ckanext-datarequests#47]
Email template reads:

An user has commented in the "Need dataset" data request. Check this new comment just in case you want to give it a reply.

You are receiving this notifications because:

* You are the owner of the data request
* You are a member of the organization where the data request has been created
* You are following the data request
* You have posted a comment in the data request

Should read:

"A" user

**Comment by nykc** [comment]
https://github.com/conwetlab/ckanext-datarequests/pull/48

I opened a pull request with the fix

**Comment by aitormagan** [comment]
Close as it's already merged.
